### ISSUE TITLE
TypeError: Image data of dtype object cannot be converted to float

### ISSUE THREAD

**Issue by 943fansi** [sreesankar711/Image-Interpolation-in-Python#1]
Could you help me to solve this problem?

**Comment by sreesankar711** [comment]
The jupyter notebook seems to be working fine. 
Please check that.  
https://github.com/sreesankar711/Image-Interpolation-in-Python/blob/main/Interpolation.ipynb

**Comment by 943fansi** [comment]
@sreesankar711 Thanks for your reply.
